insert into train (model, capacity) values ('Sable', 121);
insert into train (model, capacity) values ('Challenger', 113);
insert into train (model, capacity) values ('Cabriolet', 174);
insert into train (model, capacity) values ('Viper', 120);
insert into train (model, capacity) values ('GTI', 154);
insert into train (model, capacity) values ('90', 115);
insert into train (model, capacity) values ('Jetta', 113);
insert into train (model, capacity) values ('Bronco', 184);
insert into train (model, capacity) values ('C8 Double 12 S', 134);
insert into train (model, capacity) values ('9-5', 104);
insert into train (model, capacity) values ('Sunbird', 179);
insert into train (model, capacity) values ('Continental', 143);
insert into train (model, capacity) values ('911', 183);
insert into train (model, capacity) values ('Continental', 101);
insert into train (model, capacity) values ('Century', 148);
insert into train (model, capacity) values ('Pajero', 132);
insert into train (model, capacity) values ('Grand Am', 111);
insert into train (model, capacity) values ('Diablo', 148);
insert into train (model, capacity) values ('80', 130);
insert into train (model, capacity) values ('Savana 1500', 101);
insert into train (model, capacity) values ('Explorer', 126);
insert into train (model, capacity) values ('Corsica', 156);
insert into train (model, capacity) values ('Yukon XL 1500', 125);
insert into train (model, capacity) values ('CR-X', 188);
insert into train (model, capacity) values ('Explorer', 139);
insert into train (model, capacity) values ('FF', 186);
insert into train (model, capacity) values ('Commander', 185);
insert into train (model, capacity) values ('XLR', 110);
insert into train (model, capacity) values ('Jetta', 122);
insert into train (model, capacity) values ('MKZ', 103);
insert into train (model, capacity) values ('Grand Prix Turbo', 196);
insert into train (model, capacity) values ('XLR', 150);
insert into train (model, capacity) values ('Allroad', 133);
insert into train (model, capacity) values ('Transit Connect', 191);
insert into train (model, capacity) values ('Elantra', 178);
insert into train (model, capacity) values ('Stealth', 134);
insert into train (model, capacity) values ('Estate', 141);
insert into train (model, capacity) values ('RS 4', 123);
insert into train (model, capacity) values ('3500', 146);
insert into train (model, capacity) values ('Sebring', 165);
insert into train (model, capacity) values ('Thunderbird', 136);
insert into train (model, capacity) values ('XJ', 143);
insert into train (model, capacity) values ('Savana 3500', 169);
insert into train (model, capacity) values ('5000S', 125);
insert into train (model, capacity) values ('Impala', 105);
insert into train (model, capacity) values ('Voyager', 155);
insert into train (model, capacity) values ('CR-V', 129);
insert into train (model, capacity) values ('Colorado', 112);
insert into train (model, capacity) values ('i-Series', 150);
insert into train (model, capacity) values ('5000CS Quattro', 166);
insert into train (model, capacity) values ('D350 Club', 110);
insert into train (model, capacity) values ('Navigator', 133);
insert into train (model, capacity) values ('S40', 137);
insert into train (model, capacity) values ('Mustang', 156);
insert into train (model, capacity) values ('DeVille', 172);
insert into train (model, capacity) values ('Accord', 124);
insert into train (model, capacity) values ('E-Series', 109);
insert into train (model, capacity) values ('Legacy', 108);
insert into train (model, capacity) values ('Mark VIII', 111);
insert into train (model, capacity) values ('SRX', 123);
insert into train (model, capacity) values ('Impreza', 197);
insert into train (model, capacity) values ('Town Car', 130);
insert into train (model, capacity) values ('TSX', 118);
insert into train (model, capacity) values ('Sunbird', 126);
insert into train (model, capacity) values ('Chariot', 110);
insert into train (model, capacity) values ('Escape', 118);
insert into train (model, capacity) values ('Town Car', 100);
insert into train (model, capacity) values ('Town Car', 178);
insert into train (model, capacity) values ('Eldorado', 131);
insert into train (model, capacity) values ('XJ', 195);
insert into train (model, capacity) values ('Terraza', 106);
insert into train (model, capacity) values ('5 Series', 173);
insert into train (model, capacity) values ('LSS', 142);
insert into train (model, capacity) values ('Probe', 181);
insert into train (model, capacity) values ('Challenger', 186);
insert into train (model, capacity) values ('944', 124);
insert into train (model, capacity) values ('Camry', 111);
insert into train (model, capacity) values ('Daewoo Lacetti', 151);
insert into train (model, capacity) values ('Impreza', 198);
insert into train (model, capacity) values ('CL-Class', 167);
insert into train (model, capacity) values ('G6', 197);
insert into train (model, capacity) values ('Altima', 176);
insert into train (model, capacity) values ('Taurus', 199);
insert into train (model, capacity) values ('V8 Vantage S', 189);
insert into train (model, capacity) values ('Jetta', 108);
insert into train (model, capacity) values ('GTI', 159);
insert into train (model, capacity) values ('Colt Vista', 186);
insert into train (model, capacity) values ('Outback', 199);
insert into train (model, capacity) values ('Discovery', 178);
insert into train (model, capacity) values ('Monte Carlo', 143);
insert into train (model, capacity) values ('5 Series', 168);
insert into train (model, capacity) values ('Tempest', 105);
insert into train (model, capacity) values ('Riviera', 143);
insert into train (model, capacity) values ('Electra', 156);
insert into train (model, capacity) values ('Tribeca', 145);
insert into train (model, capacity) values ('Tacoma', 119);
insert into train (model, capacity) values ('Avalon', 179);
insert into train (model, capacity) values ('Ram 1500', 120);
insert into train (model, capacity) values ('Riviera', 118);
insert into train (model, capacity) values ('Caravan', 155);
insert into train (model, capacity) values ('Ram 1500 Club', 116);
insert into train (model, capacity) values ('Mustang', 126);
insert into train (model, capacity) values ('Malibu', 175);
insert into train (model, capacity) values ('Laser', 158);
insert into train (model, capacity) values ('GTO', 144);
insert into train (model, capacity) values ('Jetta', 103);
insert into train (model, capacity) values ('Monterey', 157);
insert into train (model, capacity) values ('Soul', 197);
insert into train (model, capacity) values ('Econoline E250', 142);
insert into train (model, capacity) values ('Outlook', 104);
insert into train (model, capacity) values ('Sebring', 116);
insert into train (model, capacity) values ('Skylark', 194);
insert into train (model, capacity) values ('Titan', 141);
insert into train (model, capacity) values ('Achieva', 171);
insert into train (model, capacity) values ('Mazda3', 109);
insert into train (model, capacity) values ('9-2X', 109);
insert into train (model, capacity) values ('Miata MX-5', 162);
insert into train (model, capacity) values ('900', 107);
insert into train (model, capacity) values ('Ranger', 141);
insert into train (model, capacity) values ('Cressida', 188);
insert into train (model, capacity) values ('Justy', 176);
insert into train (model, capacity) values ('1 Series', 140);
insert into train (model, capacity) values ('Intrepid', 195);
insert into train (model, capacity) values ('Protege', 124);
insert into train (model, capacity) values ('Ram', 163);
insert into train (model, capacity) values ('Taurus', 131);
insert into train (model, capacity) values ('Accent', 182);
insert into train (model, capacity) values ('Express', 105);
insert into train (model, capacity) values ('Tacoma Xtra', 132);
insert into train (model, capacity) values ('Sentra', 103);
insert into train (model, capacity) values ('Expedition', 176);
insert into train (model, capacity) values ('MPV', 100);
insert into train (model, capacity) values ('Tahoe', 114);
insert into train (model, capacity) values ('Montero', 179);
insert into train (model, capacity) values ('DeVille', 188);
insert into train (model, capacity) values ('Sequoia', 192);
insert into train (model, capacity) values ('5 Series', 168);
insert into train (model, capacity) values ('Ranger', 166);
insert into train (model, capacity) values ('Town Car', 194);
insert into train (model, capacity) values ('Sonata', 148);
insert into train (model, capacity) values ('Nitro', 120);
insert into train (model, capacity) values ('Mazda6', 163);
insert into train (model, capacity) values ('928', 101);
insert into train (model, capacity) values ('Grand Prix', 121);
insert into train (model, capacity) values ('Suburban 2500', 142);
insert into train (model, capacity) values ('MX-3', 170);
insert into train (model, capacity) values ('612 Scaglietti', 161);
insert into train (model, capacity) values ('Corolla', 146);
insert into train (model, capacity) values ('Riviera', 177);
insert into train (model, capacity) values ('Murciélago', 185);
insert into train (model, capacity) values ('Land Cruiser', 118);
insert into train (model, capacity) values ('Ram 3500 Club', 151);
insert into train (model, capacity) values ('Rainier', 199);
insert into train (model, capacity) values ('IS', 192);
insert into train (model, capacity) values ('Vibe', 198);
insert into train (model, capacity) values ('Mystique', 173);
insert into train (model, capacity) values ('Camry', 154);
insert into train (model, capacity) values ('S60', 108);
insert into train (model, capacity) values ('MDX', 103);
insert into train (model, capacity) values ('MDX', 199);
insert into train (model, capacity) values ('Lancer', 132);
insert into train (model, capacity) values ('5 Series', 132);
insert into train (model, capacity) values ('Journey', 159);
insert into train (model, capacity) values ('Mazdaspeed 3', 110);
insert into train (model, capacity) values ('Odyssey', 109);
insert into train (model, capacity) values ('Discovery', 179);
insert into train (model, capacity) values ('911', 180);
insert into train (model, capacity) values ('S4', 144);
insert into train (model, capacity) values ('G-Series G10', 105);
insert into train (model, capacity) values ('Catera', 181);
insert into train (model, capacity) values ('Grand Vitara', 108);
insert into train (model, capacity) values ('Summit', 174);
insert into train (model, capacity) values ('Neon', 198);
insert into train (model, capacity) values ('Crown Victoria', 187);
insert into train (model, capacity) values ('Metro', 153);
insert into train (model, capacity) values ('Tahoe', 179);
insert into train (model, capacity) values ('Passat', 188);
insert into train (model, capacity) values ('Murciélago', 170);
insert into train (model, capacity) values ('RX', 140);
insert into train (model, capacity) values ('Outlander', 110);
insert into train (model, capacity) values ('Coupe', 163);
insert into train (model, capacity) values ('Jetta III', 138);
insert into train (model, capacity) values ('GS', 165);
insert into train (model, capacity) values ('V50', 153);
insert into train (model, capacity) values ('Achieva', 153);
insert into train (model, capacity) values ('TundraMax', 130);
insert into train (model, capacity) values ('H1', 182);
insert into train (model, capacity) values ('Savana 2500', 123);
insert into train (model, capacity) values ('A3', 180);
insert into train (model, capacity) values ('Cabriolet', 125);
insert into train (model, capacity) values ('S-Class', 133);
insert into train (model, capacity) values ('Wrangler', 124);
insert into train (model, capacity) values ('Metro', 200);
insert into train (model, capacity) values ('Town Car', 122);
insert into train (model, capacity) values ('Stratus', 128);
insert into train (model, capacity) values ('Aztek', 139);
insert into train (model, capacity) values ('Murciélago', 165);
insert into train (model, capacity) values ('Riviera', 120);
insert into train (model, capacity) values ('Suburban 1500', 172);
insert into train (model, capacity) values ('Grand Prix', 155);
insert into train (model, capacity) values ('VUE', 121);
insert into train (model, capacity) values ('F250', 128);
insert into train (model, capacity) values ('Ranger', 183);
insert into train (model, capacity) values ('F250', 145);
insert into train (model, capacity) values ('Econoline E350', 111);
insert into train (model, capacity) values ('Jetta', 171);
insert into train (model, capacity) values ('LTD', 186);
insert into train (model, capacity) values ('Truck', 150);
insert into train (model, capacity) values ('Sky', 176);
insert into train (model, capacity) values ('G-Series G30', 157);
insert into train (model, capacity) values ('Grand Prix', 189);
insert into train (model, capacity) values ('Explorer', 137);
insert into train (model, capacity) values ('Grand Prix', 162);
insert into train (model, capacity) values ('G-Series 2500', 105);
insert into train (model, capacity) values ('Dakota', 158);
insert into train (model, capacity) values ('3500', 155);
insert into train (model, capacity) values ('V70', 182);
insert into train (model, capacity) values ('LR3', 171);
insert into train (model, capacity) values ('Skylark', 133);
insert into train (model, capacity) values ('911', 104);
insert into train (model, capacity) values ('E-Class', 100);
insert into train (model, capacity) values ('G35', 106);
insert into train (model, capacity) values ('Silhouette', 158);
insert into train (model, capacity) values ('E-Class', 190);
insert into train (model, capacity) values ('GTO', 116);
insert into train (model, capacity) values ('Insight', 161);
insert into train (model, capacity) values ('V70', 177);
insert into train (model, capacity) values ('Sterling', 162);
insert into train (model, capacity) values ('Matrix', 129);
insert into train (model, capacity) values ('Grand Caravan', 191);
insert into train (model, capacity) values ('Odyssey', 138);
insert into train (model, capacity) values ('Mustang', 193);
insert into train (model, capacity) values ('GT500', 118);
insert into train (model, capacity) values ('STS', 100);
insert into train (model, capacity) values ('Accord', 176);
insert into train (model, capacity) values ('S8', 142);
insert into train (model, capacity) values ('Explorer Sport', 137);
insert into train (model, capacity) values ('Monte Carlo', 169);
insert into train (model, capacity) values ('Prizm', 184);
insert into train (model, capacity) values ('Intrepid', 100);
insert into train (model, capacity) values ('A4', 180);
insert into train (model, capacity) values ('Versa', 176);
insert into train (model, capacity) values ('Justy', 162);
insert into train (model, capacity) values ('CX', 110);
insert into train (model, capacity) values ('MKZ', 152);
insert into train (model, capacity) values ('Courier', 182);
insert into train (model, capacity) values ('626', 175);
insert into train (model, capacity) values ('Galant', 157);
insert into train (model, capacity) values ('S60', 140);
insert into train (model, capacity) values ('Cirrus', 170);
insert into train (model, capacity) values ('SRX', 137);
insert into train (model, capacity) values ('Focus', 143);
insert into train (model, capacity) values ('Grand Prix', 118);
insert into train (model, capacity) values ('Mazda6', 128);
insert into train (model, capacity) values ('S80', 169);
insert into train (model, capacity) values ('Sonata', 104);
insert into train (model, capacity) values ('A5', 101);
insert into train (model, capacity) values ('Avalanche 2500', 154);
insert into train (model, capacity) values ('900', 169);
insert into train (model, capacity) values ('Corvette', 135);
insert into train (model, capacity) values ('S-Class', 128);
insert into train (model, capacity) values ('600', 176);
insert into train (model, capacity) values ('Outback', 125);
insert into train (model, capacity) values ('CTS-V', 193);
insert into train (model, capacity) values ('Exige', 107);
insert into train (model, capacity) values ('Ram Van 1500', 114);
insert into train (model, capacity) values ('Xtra', 176);
insert into train (model, capacity) values ('Jetta', 151);
insert into train (model, capacity) values ('Monte Carlo', 194);
insert into train (model, capacity) values ('Bronco II', 147);
insert into train (model, capacity) values ('QX', 145);
insert into train (model, capacity) values ('Celica', 156);
insert into train (model, capacity) values ('Rally Wagon 2500', 180);
insert into train (model, capacity) values ('Escape', 119);
insert into train (model, capacity) values ('Quest', 121);
insert into train (model, capacity) values ('GTO', 179);
insert into train (model, capacity) values ('Camaro', 161);
insert into train (model, capacity) values ('430', 123);
insert into train (model, capacity) values ('Ram', 180);
insert into train (model, capacity) values ('XJ Series', 186);
insert into train (model, capacity) values ('Quest', 177);
insert into train (model, capacity) values ('G-Series 2500', 105);
insert into train (model, capacity) values ('GTI', 190);
insert into train (model, capacity) values ('Roadmaster', 165);
insert into train (model, capacity) values ('Mountaineer', 117);
insert into train (model, capacity) values ('Countach', 137);
insert into train (model, capacity) values ('Sierra 2500', 169);
insert into train (model, capacity) values ('350Z', 158);
insert into train (model, capacity) values ('M5', 197);
insert into train (model, capacity) values ('Boxster', 187);
insert into train (model, capacity) values ('Avenger', 178);
insert into train (model, capacity) values ('Taurus', 197);
insert into train (model, capacity) values ('SJ', 119);
insert into train (model, capacity) values ('Accord', 145);
insert into train (model, capacity) values ('Supra', 100);
insert into train (model, capacity) values ('MKZ', 146);
insert into train (model, capacity) values ('928', 109);
insert into train (model, capacity) values ('Legacy', 193);
insert into train (model, capacity) values ('645', 113);
insert into train (model, capacity) values ('Sonata', 173);
insert into train (model, capacity) values ('Scoupe', 104);
insert into train (model, capacity) values ('Corolla', 197);
insert into train (model, capacity) values ('760', 124);
insert into train (model, capacity) values ('Cherokee', 199);
insert into train (model, capacity) values ('Sienna', 102);
insert into train (model, capacity) values ('Sportage', 175);
insert into train (model, capacity) values ('S-Class', 173);
insert into train (model, capacity) values ('Versa', 141);
insert into train (model, capacity) values ('Forenza', 153);
insert into train (model, capacity) values ('Acadia', 182);
insert into train (model, capacity) values ('Q', 169);
insert into train (model, capacity) values ('Civic', 186);
insert into train (model, capacity) values ('Trans Sport', 159);
insert into train (model, capacity) values ('C70', 104);
insert into train (model, capacity) values ('Summit', 165);
insert into train (model, capacity) values ('Challenger', 186);
insert into train (model, capacity) values ('A8', 190);
insert into train (model, capacity) values ('riolet', 170);
insert into train (model, capacity) values ('Roadster', 106);
insert into train (model, capacity) values ('Park Avenue', 164);
insert into train (model, capacity) values ('Durango', 158);
insert into train (model, capacity) values ('C-Class', 146);
insert into train (model, capacity) values ('Rally Wagon 1500', 143);
insert into train (model, capacity) values ('LS', 101);
insert into train (model, capacity) values ('LHS', 128);
insert into train (model, capacity) values ('RX-7', 117);
insert into train (model, capacity) values ('Freestar', 171);
insert into train (model, capacity) values ('G-Series 2500', 153);
insert into train (model, capacity) values ('CLK-Class', 105);
insert into train (model, capacity) values ('Golf', 167);
insert into train (model, capacity) values ('Legend', 194);
insert into train (model, capacity) values ('XK Series', 139);
insert into train (model, capacity) values ('Expo', 157);
insert into train (model, capacity) values ('MPV', 171);
insert into train (model, capacity) values ('Rainier', 199);
insert into train (model, capacity) values ('Eos', 111);
insert into train (model, capacity) values ('Tiburon', 110);
insert into train (model, capacity) values ('Tundra', 126);
insert into train (model, capacity) values ('Corolla', 159);
insert into train (model, capacity) values ('Protege', 178);
insert into train (model, capacity) values ('Crown Victoria', 167);
insert into train (model, capacity) values ('Grand Prix', 117);
insert into train (model, capacity) values ('Jetta', 145);
insert into train (model, capacity) values ('Cordia', 172);
insert into train (model, capacity) values ('GTO', 169);
insert into train (model, capacity) values ('Eclipse', 112);
insert into train (model, capacity) values ('Firebird', 173);
insert into train (model, capacity) values ('RX Hybrid', 129);
insert into train (model, capacity) values ('Tundra', 114);
insert into train (model, capacity) values ('Quest', 157);
insert into train (model, capacity) values ('Ram 1500 Club', 158);
insert into train (model, capacity) values ('Cavalier', 147);
insert into train (model, capacity) values ('3 Series', 160);
insert into train (model, capacity) values ('9-7X', 199);
insert into train (model, capacity) values ('RSX', 190);
insert into train (model, capacity) values ('Ram Van 1500', 123);
insert into train (model, capacity) values ('F350', 155);
insert into train (model, capacity) values ('Cayman', 104);
insert into train (model, capacity) values ('Solara', 115);
insert into train (model, capacity) values ('XC70', 108);
insert into train (model, capacity) values ('xA', 179);
insert into train (model, capacity) values ('xB', 185);
insert into train (model, capacity) values ('Ram 2500', 117);
insert into train (model, capacity) values ('Tracker', 117);
insert into train (model, capacity) values ('Sonoma Club Coupe', 149);
insert into train (model, capacity) values ('V40', 103);
insert into train (model, capacity) values ('XJ', 138);
insert into train (model, capacity) values ('200SX', 149);
insert into train (model, capacity) values ('Quest', 109);
insert into train (model, capacity) values ('F-Series', 138);
insert into train (model, capacity) values ('Supra', 113);
insert into train (model, capacity) values ('Golf', 152);
insert into train (model, capacity) values ('Grand Am', 115);
insert into train (model, capacity) values ('Exige', 123);
insert into train (model, capacity) values ('Skylark', 112);
insert into train (model, capacity) values ('V70', 101);
insert into train (model, capacity) values ('Passat', 165);
insert into train (model, capacity) values ('Altima', 142);
insert into train (model, capacity) values ('Savana 3500', 143);
insert into train (model, capacity) values ('Breeze', 174);
insert into train (model, capacity) values ('Seville', 167);
insert into train (model, capacity) values ('Jimmy', 192);
insert into train (model, capacity) values ('MKZ', 165);
insert into train (model, capacity) values ('RX Hybrid', 107);
insert into train (model, capacity) values ('Protege', 115);
insert into train (model, capacity) values ('Type-1h', 157);
insert into train (model, capacity) values ('Mazda5', 131);
insert into train (model, capacity) values ('X3', 194);
insert into train (model, capacity) values ('EXP', 108);
insert into train (model, capacity) values ('ES', 190);
insert into train (model, capacity) values ('Leganza', 153);
insert into train (model, capacity) values ('Yukon XL 2500', 114);
insert into train (model, capacity) values ('545', 129);
insert into train (model, capacity) values ('Phaeton', 196);
insert into train (model, capacity) values ('XJ', 172);
insert into train (model, capacity) values ('Azera', 122);
insert into train (model, capacity) values ('Galant', 100);
insert into train (model, capacity) values ('SSR', 153);
insert into train (model, capacity) values ('3 Series', 103);
insert into train (model, capacity) values ('Mulsanne', 145);
insert into train (model, capacity) values ('Cayenne', 141);
insert into train (model, capacity) values ('F250', 165);
insert into train (model, capacity) values ('Sunbird', 134);
insert into train (model, capacity) values ('Park Avenue', 179);
insert into train (model, capacity) values ('Turbo Firefly', 154);
insert into train (model, capacity) values ('G-Class', 177);
insert into train (model, capacity) values ('GTI', 148);
insert into train (model, capacity) values ('Sable', 128);
insert into train (model, capacity) values ('Golf', 126);
insert into train (model, capacity) values ('Corvette', 169);
insert into train (model, capacity) values ('Torino', 185);
insert into train (model, capacity) values ('Impala', 157);
insert into train (model, capacity) values ('Xterra', 114);
insert into train (model, capacity) values ('Golf III', 123);
insert into train (model, capacity) values ('Lancer', 125);
insert into train (model, capacity) values ('LTD', 192);
insert into train (model, capacity) values ('1 Series', 123);
insert into train (model, capacity) values ('Alero', 181);
insert into train (model, capacity) values ('Pilot', 189);
insert into train (model, capacity) values ('Sierra', 181);
insert into train (model, capacity) values ('Swift', 100);
insert into train (model, capacity) values ('Eclipse', 108);
insert into train (model, capacity) values ('Yukon', 164);
insert into train (model, capacity) values ('Santa Fe', 137);
insert into train (model, capacity) values ('Tucson', 129);
insert into train (model, capacity) values ('Yaris', 154);
insert into train (model, capacity) values ('Explorer', 131);
insert into train (model, capacity) values ('Raider', 132);
insert into train (model, capacity) values ('GTI', 166);
insert into train (model, capacity) values ('Sienna', 186);
insert into train (model, capacity) values ('RX', 102);
insert into train (model, capacity) values ('Mark LT', 154);
insert into train (model, capacity) values ('Mazda6', 105);
insert into train (model, capacity) values ('S10', 104);
insert into train (model, capacity) values ('MX-5', 107);
insert into train (model, capacity) values ('B-Series', 137);
insert into train (model, capacity) values ('Mountaineer', 198);
insert into train (model, capacity) values ('Land Cruiser', 134);
insert into train (model, capacity) values ('Jetta', 165);
insert into train (model, capacity) values ('E-Series', 164);
insert into train (model, capacity) values ('MKX', 130);
insert into train (model, capacity) values ('MPV', 116);
insert into train (model, capacity) values ('Equator', 163);
insert into train (model, capacity) values ('EX', 127);
insert into train (model, capacity) values ('Durango', 118);
insert into train (model, capacity) values ('MDX', 152);
insert into train (model, capacity) values ('Express 1500', 107);
insert into train (model, capacity) values ('Firefly', 164);
insert into train (model, capacity) values ('XK', 192);
insert into train (model, capacity) values ('Summit', 102);
insert into train (model, capacity) values ('Corrado', 160);
insert into train (model, capacity) values ('GTO', 187);
insert into train (model, capacity) values ('Ridgeline', 157);
insert into train (model, capacity) values ('Viper', 151);
insert into train (model, capacity) values ('F150', 154);
insert into train (model, capacity) values ('RX-7', 126);
insert into train (model, capacity) values ('Cougar', 158);
insert into train (model, capacity) values ('Escalade', 180);
insert into train (model, capacity) values ('F150', 118);
insert into train (model, capacity) values ('Mystique', 150);
insert into train (model, capacity) values ('CLK-Class', 119);
insert into train (model, capacity) values ('X-Type', 171);
insert into train (model, capacity) values ('Cooper', 151);
insert into train (model, capacity) values ('IS', 186);
insert into train (model, capacity) values ('Tempest', 114);
insert into train (model, capacity) values ('Express 3500', 153);
insert into train (model, capacity) values ('Park Avenue', 139);
insert into train (model, capacity) values ('Vandura G3500', 182);
insert into train (model, capacity) values ('900', 164);
insert into train (model, capacity) values ('Accord Crosstour', 125);
insert into train (model, capacity) values ('Vega', 184);
insert into train (model, capacity) values ('Yukon XL 2500', 171);
insert into train (model, capacity) values ('Savana', 105);
insert into train (model, capacity) values ('Aveo', 136);
insert into train (model, capacity) values ('Grand Prix', 178);
insert into train (model, capacity) values ('A4', 174);
insert into train (model, capacity) values ('S-Series', 128);
insert into train (model, capacity) values ('TL', 102);
insert into train (model, capacity) values ('X6 M', 190);
insert into train (model, capacity) values ('Eclipse', 187);
insert into train (model, capacity) values ('Seville', 171);
insert into train (model, capacity) values ('Mazda3', 118);
insert into train (model, capacity) values ('S90', 116);
insert into train (model, capacity) values ('Civic', 175);
insert into train (model, capacity) values ('Grand Marquis', 196);
insert into train (model, capacity) values ('Maxima', 121);
insert into train (model, capacity) values ('Silverado 3500', 198);
insert into train (model, capacity) values ('S-Series', 133);
insert into train (model, capacity) values ('Dakota', 121);
insert into train (model, capacity) values ('Civic', 187);
insert into train (model, capacity) values ('Equinox', 121);
insert into train (model, capacity) values ('Suburban 1500', 179);
insert into train (model, capacity) values ('Tahoe', 146);
insert into train (model, capacity) values ('DeVille', 100);
insert into train (model, capacity) values ('XK Series', 152);
insert into train (model, capacity) values ('Caprice', 131);
insert into train (model, capacity) values ('5000S', 139);
insert into train (model, capacity) values ('G35', 126);
insert into train (model, capacity) values ('Aurora', 173);
insert into train (model, capacity) values ('Tribeca', 136);
insert into train (model, capacity) values ('Range Rover', 189);
insert into train (model, capacity) values ('Supra', 184);
insert into train (model, capacity) values ('H3', 139);
insert into train (model, capacity) values ('MDX', 188);
insert into train (model, capacity) values ('Charger', 105);
insert into train (model, capacity) values ('Truck', 185);
insert into train (model, capacity) values ('4000s Quattro', 133);
insert into train (model, capacity) values ('Sierra 1500', 195);
insert into train (model, capacity) values ('F150', 135);
insert into train (model, capacity) values ('Tredia', 101);
insert into train (model, capacity) values ('Raider', 106);
insert into train (model, capacity) values ('Lumina', 194);
insert into train (model, capacity) values ('911', 197);
insert into train (model, capacity) values ('300M', 104);
insert into train (model, capacity) values ('3000GT', 184);
insert into train (model, capacity) values ('Blackwood', 121);
insert into train (model, capacity) values ('Cavalier', 177);
insert into train (model, capacity) values ('Miata MX-5', 170);
insert into train (model, capacity) values ('500SEC', 107);
insert into train (model, capacity) values ('Pajero', 166);
insert into train (model, capacity) values ('Imperial', 194);
insert into train (model, capacity) values ('F150', 118);
insert into train (model, capacity) values ('Rainier', 167);
insert into train (model, capacity) values ('2500', 154);
insert into train (model, capacity) values ('TundraMax', 130);
insert into train (model, capacity) values ('Colt', 185);
insert into train (model, capacity) values ('Justy', 175);
insert into train (model, capacity) values ('2500 Club Coupe', 154);
insert into train (model, capacity) values ('Dakota', 151);
insert into train (model, capacity) values ('911', 187);
insert into train (model, capacity) values ('B-Series Plus', 132);
insert into train (model, capacity) values ('Fox', 153);
insert into train (model, capacity) values ('968', 167);
insert into train (model, capacity) values ('GT500', 116);
insert into train (model, capacity) values ('E350', 121);
insert into train (model, capacity) values ('Sonata', 180);
insert into train (model, capacity) values ('100', 167);
insert into train (model, capacity) values ('C70', 117);
insert into train (model, capacity) values ('Caprice', 120);
insert into train (model, capacity) values ('B2500', 143);
insert into train (model, capacity) values ('Town Car', 131);
insert into train (model, capacity) values ('GranTurismo', 151);
insert into train (model, capacity) values ('Quattroporte', 137);
insert into train (model, capacity) values ('Prius', 159);
insert into train (model, capacity) values ('3500', 122);
insert into train (model, capacity) values ('Highlander', 133);
insert into train (model, capacity) values ('Lancer Evolution', 116);
insert into train (model, capacity) values ('Express 3500', 142);
insert into train (model, capacity) values ('Yukon', 148);
insert into train (model, capacity) values ('XC60', 102);
insert into train (model, capacity) values ('Esteem', 122);
insert into train (model, capacity) values ('Frontier', 106);
insert into train (model, capacity) values ('Ram Van 2500', 106);
insert into train (model, capacity) values ('Tracer', 105);
insert into train (model, capacity) values ('Impreza', 122);
insert into train (model, capacity) values ('C-Class', 101);
insert into train (model, capacity) values ('SL-Class', 168);
insert into train (model, capacity) values ('Mighty Max Macro', 155);
insert into train (model, capacity) values ('S40', 190);
insert into train (model, capacity) values ('Bronco II', 109);
insert into train (model, capacity) values ('Maxima', 123);
insert into train (model, capacity) values ('Nitro', 182);
insert into train (model, capacity) values ('PT Cruiser', 141);
insert into train (model, capacity) values ('Eurovan', 183);
insert into train (model, capacity) values ('X3', 147);
insert into train (model, capacity) values ('G-Series 1500', 137);
insert into train (model, capacity) values ('LeMans', 105);
insert into train (model, capacity) values ('STS', 126);
insert into train (model, capacity) values ('G-Series G10', 120);
insert into train (model, capacity) values ('F150', 197);
insert into train (model, capacity) values ('xA', 195);
insert into train (model, capacity) values ('CC', 182);
insert into train (model, capacity) values ('Crossfire', 120);
insert into train (model, capacity) values ('Yukon XL 2500', 127);
insert into train (model, capacity) values ('Savana 3500', 199);
insert into train (model, capacity) values ('C/V', 128);
insert into train (model, capacity) values ('A8', 161);
insert into train (model, capacity) values ('Escape', 170);
insert into train (model, capacity) values ('Fortwo', 123);
insert into train (model, capacity) values ('Explorer Sport Trac', 187);
insert into train (model, capacity) values ('M3', 119);
insert into train (model, capacity) values ('Range Rover Evoque', 158);
insert into train (model, capacity) values ('Suburban 1500', 166);
insert into train (model, capacity) values ('Metro', 194);
insert into train (model, capacity) values ('IS', 123);
insert into train (model, capacity) values ('IPL G', 143);
insert into train (model, capacity) values ('Tercel', 108);
insert into train (model, capacity) values ('Mighty Max', 139);
insert into train (model, capacity) values ('Celica', 178);
insert into train (model, capacity) values ('E250', 187);
insert into train (model, capacity) values ('F-Series', 126);
insert into train (model, capacity) values ('TrailBlazer', 109);
insert into train (model, capacity) values ('Avenger', 101);
insert into train (model, capacity) values ('Sierra 3500', 177);
insert into train (model, capacity) values ('Savana 1500', 115);
insert into train (model, capacity) values ('Galant', 198);
insert into train (model, capacity) values ('Exige', 161);
insert into train (model, capacity) values ('Sebring', 112);
insert into train (model, capacity) values ('Montero', 104);
insert into train (model, capacity) values ('Lucerne', 130);
insert into train (model, capacity) values ('Canyon', 148);
insert into train (model, capacity) values ('LS', 110);
insert into train (model, capacity) values ('Swift', 134);
insert into train (model, capacity) values ('IS', 138);
insert into train (model, capacity) values ('4Runner', 128);
insert into train (model, capacity) values ('Cooper Clubman', 122);
insert into train (model, capacity) values ('SL-Class', 123);
insert into train (model, capacity) values ('Tahoe', 118);
insert into train (model, capacity) values ('Probe', 130);
insert into train (model, capacity) values ('Entourage', 120);
insert into train (model, capacity) values ('S2000', 194);
insert into train (model, capacity) values ('Alero', 144);
insert into train (model, capacity) values ('Viper', 145);
insert into train (model, capacity) values ('Accord', 196);
insert into train (model, capacity) values ('5 Series', 168);
insert into train (model, capacity) values ('Vibe', 192);
insert into train (model, capacity) values ('S80', 127);
insert into train (model, capacity) values ('Highlander', 193);
insert into train (model, capacity) values ('Econoline E250', 135);
insert into train (model, capacity) values ('Montana SV6', 106);
insert into train (model, capacity) values ('5000CS Quattro', 168);
insert into train (model, capacity) values ('G-Class', 137);
insert into train (model, capacity) values ('Previa', 128);
insert into train (model, capacity) values ('Fusion', 184);
insert into train (model, capacity) values ('Phantom', 109);
insert into train (model, capacity) values ('Excursion', 134);
insert into train (model, capacity) values ('Ram 3500', 156);
insert into train (model, capacity) values ('3500', 100);
insert into train (model, capacity) values ('Elise', 167);
insert into train (model, capacity) values ('A8', 137);
insert into train (model, capacity) values ('Caliber', 174);
insert into train (model, capacity) values ('Grand Marquis', 131);
insert into train (model, capacity) values ('Ciera', 107);
insert into train (model, capacity) values ('Axiom', 133);
insert into train (model, capacity) values ('Eurovan', 172);
insert into train (model, capacity) values ('MX-5', 102);
insert into train (model, capacity) values ('Caliber', 132);
insert into train (model, capacity) values ('Firefly', 113);
insert into train (model, capacity) values ('Impreza WRX', 131);
insert into train (model, capacity) values ('Daewoo Lacetti', 143);
insert into train (model, capacity) values ('XLR', 132);
insert into train (model, capacity) values ('Savana 3500', 156);
insert into train (model, capacity) values ('Cherokee', 197);
insert into train (model, capacity) values ('Dakota Club', 170);
insert into train (model, capacity) values ('Range Rover', 115);
insert into train (model, capacity) values ('Sephia', 180);
insert into train (model, capacity) values ('960', 200);
insert into train (model, capacity) values ('Montero', 159);
insert into train (model, capacity) values ('Mighty Max Macro', 162);
insert into train (model, capacity) values ('Astro', 167);
insert into train (model, capacity) values ('300', 105);
insert into train (model, capacity) values ('LTD', 162);
insert into train (model, capacity) values ('Yukon XL 1500', 190);
insert into train (model, capacity) values ('Escalade', 120);
insert into train (model, capacity) values ('Avalanche', 200);
insert into train (model, capacity) values ('Mustang', 144);
insert into train (model, capacity) values ('G55 AMG', 142);
insert into train (model, capacity) values ('Miata MX-5', 129);
insert into train (model, capacity) values ('Silverado 1500', 115);
insert into train (model, capacity) values ('Firebird Formula', 159);
insert into train (model, capacity) values ('Vibe', 139);
insert into train (model, capacity) values ('Camaro', 190);
insert into train (model, capacity) values ('911', 196);
insert into train (model, capacity) values ('Regal', 117);
insert into train (model, capacity) values ('GS', 105);
insert into train (model, capacity) values ('Ram 1500 Club', 123);
insert into train (model, capacity) values ('Tahoe', 161);
insert into train (model, capacity) values ('3 Series', 170);
insert into train (model, capacity) values ('C-Class', 194);
insert into train (model, capacity) values ('Elantra', 183);
insert into train (model, capacity) values ('MX-5', 146);
insert into train (model, capacity) values ('XJ', 167);
insert into train (model, capacity) values ('Montego', 103);
insert into train (model, capacity) values ('CLK-Class', 103);
insert into train (model, capacity) values ('90', 102);
insert into train (model, capacity) values ('Capri', 169);
insert into train (model, capacity) values ('57', 113);
insert into train (model, capacity) values ('Range Rover', 139);
insert into train (model, capacity) values ('Econoline E350', 165);
insert into train (model, capacity) values ('Fiero', 121);
insert into train (model, capacity) values ('F150', 187);
insert into train (model, capacity) values ('Villager', 135);
insert into train (model, capacity) values ('Grand Am', 168);
insert into train (model, capacity) values ('8 Series', 195);
insert into train (model, capacity) values ('Odyssey', 110);
insert into train (model, capacity) values ('Ranger', 154);
insert into train (model, capacity) values ('Z4', 199);
insert into train (model, capacity) values ('LaCrosse', 119);
insert into train (model, capacity) values ('Bonneville', 111);
insert into train (model, capacity) values ('Prius Plug-in Hybrid', 125);
insert into train (model, capacity) values ('LHS', 195);
insert into train (model, capacity) values ('Mountaineer', 178);
insert into train (model, capacity) values ('Charger', 159);
insert into train (model, capacity) values ('Rogue', 163);
insert into train (model, capacity) values ('Forte', 143);
insert into train (model, capacity) values ('Imperial', 183);
insert into train (model, capacity) values ('Cobalt', 165);
insert into train (model, capacity) values ('Lumina', 121);
insert into train (model, capacity) values ('300SD', 150);
insert into train (model, capacity) values ('S-Class', 120);
insert into train (model, capacity) values ('Grand Caravan', 157);
insert into train (model, capacity) values ('928', 133);
insert into train (model, capacity) values ('Golf', 106);
insert into train (model, capacity) values ('Land Cruiser', 197);
insert into train (model, capacity) values ('MKZ', 171);
insert into train (model, capacity) values ('Impreza', 136);
insert into train (model, capacity) values ('Bonneville', 170);
insert into train (model, capacity) values ('Stratus', 185);
insert into train (model, capacity) values ('Phantom', 178);
insert into train (model, capacity) values ('CLS-Class', 106);
insert into train (model, capacity) values ('M3', 156);
insert into train (model, capacity) values ('rio', 151);
insert into train (model, capacity) values ('Eurovan', 128);
insert into train (model, capacity) values ('Lancer Evolution', 195);
insert into train (model, capacity) values ('S10', 151);
insert into train (model, capacity) values ('Arnage', 171);
insert into train (model, capacity) values ('RX-8', 110);
insert into train (model, capacity) values ('Riviera', 152);
insert into train (model, capacity) values ('Rodeo', 160);
insert into train (model, capacity) values ('Villager', 198);
insert into train (model, capacity) values ('Wrangler', 131);
insert into train (model, capacity) values ('Legend', 130);
insert into train (model, capacity) values ('MR2', 192);
insert into train (model, capacity) values ('88', 178);
insert into train (model, capacity) values ('Colt Vista', 105);
insert into train (model, capacity) values ('SRX', 108);
insert into train (model, capacity) values ('Escalade ESV', 190);
insert into train (model, capacity) values ('B-Series', 164);
insert into train (model, capacity) values ('ES', 153);
insert into train (model, capacity) values ('ES', 162);
insert into train (model, capacity) values ('HS', 141);
insert into train (model, capacity) values ('Santa Fe', 133);
insert into train (model, capacity) values ('Classic', 143);
insert into train (model, capacity) values ('Sundance', 129);
insert into train (model, capacity) values ('Titan', 108);
insert into train (model, capacity) values ('Explorer Sport', 136);
insert into train (model, capacity) values ('Spyder', 150);
insert into train (model, capacity) values ('C-Class', 133);
insert into train (model, capacity) values ('Town & Country', 189);
insert into train (model, capacity) values ('Laser', 136);
insert into train (model, capacity) values ('Colorado', 182);
insert into train (model, capacity) values ('Mulsanne', 186);
insert into train (model, capacity) values ('MKX', 138);
insert into train (model, capacity) values ('Range Rover', 194);
insert into train (model, capacity) values ('Monte Carlo', 116);
insert into train (model, capacity) values ('Grand Caravan', 141);
insert into train (model, capacity) values ('Colorado', 109);
insert into train (model, capacity) values ('TSX', 162);
insert into train (model, capacity) values ('Boxster', 126);
insert into train (model, capacity) values ('Boxster', 169);
insert into train (model, capacity) values ('B-Series Plus', 161);
insert into train (model, capacity) values ('MPV', 147);
insert into train (model, capacity) values ('Tempest', 130);
insert into train (model, capacity) values ('Sunbird', 152);
insert into train (model, capacity) values ('300', 157);
insert into train (model, capacity) values ('Monterey', 119);
insert into train (model, capacity) values ('Eclipse', 154);
insert into train (model, capacity) values ('5 Series', 136);
insert into train (model, capacity) values ('Pajero', 160);
insert into train (model, capacity) values ('Genesis Coupe', 164);
insert into train (model, capacity) values ('riolet', 130);
insert into train (model, capacity) values ('Armada', 195);
insert into train (model, capacity) values ('Forester', 117);
insert into train (model, capacity) values ('Mustang', 170);
insert into train (model, capacity) values ('Grand Cherokee', 162);
insert into train (model, capacity) values ('Capri', 154);
insert into train (model, capacity) values ('Supra', 195);
insert into train (model, capacity) values ('Z4 M', 105);
insert into train (model, capacity) values ('Ram 50', 110);
insert into train (model, capacity) values ('Dakota', 142);
insert into train (model, capacity) values ('Jetta', 136);
insert into train (model, capacity) values ('Dakota', 126);
insert into train (model, capacity) values ('Corsica', 109);
insert into train (model, capacity) values ('Grand Marquis', 145);
insert into train (model, capacity) values ('LS', 127);
insert into train (model, capacity) values ('3 Series', 155);
insert into train (model, capacity) values ('A5', 136);
insert into train (model, capacity) values ('Caravan', 177);
insert into train (model, capacity) values ('TrailBlazer', 180);
insert into train (model, capacity) values ('430', 116);
insert into train (model, capacity) values ('Intrepid', 188);
insert into train (model, capacity) values ('LX', 117);
insert into train (model, capacity) values ('Topaz', 111);
insert into train (model, capacity) values ('X6', 160);
insert into train (model, capacity) values ('Escalade ESV', 133);
insert into train (model, capacity) values ('Precis', 155);
insert into train (model, capacity) values ('Celica', 104);
insert into train (model, capacity) values ('Escort', 192);
insert into train (model, capacity) values ('A6', 112);
insert into train (model, capacity) values ('Discovery', 177);
insert into train (model, capacity) values ('Aerio', 193);
insert into train (model, capacity) values ('Coachbuilder', 152);
insert into train (model, capacity) values ('928', 148);
insert into train (model, capacity) values ('Cobalt', 190);
insert into train (model, capacity) values ('Spyder', 135);
insert into train (model, capacity) values ('Tahoe', 105);
insert into train (model, capacity) values ('Spectra', 124);
insert into train (model, capacity) values ('Aerio', 108);
insert into train (model, capacity) values ('H1', 129);
insert into train (model, capacity) values ('Fusion', 148);
insert into train (model, capacity) values ('Ram 2500', 151);
insert into train (model, capacity) values ('Cavalier', 170);
insert into train (model, capacity) values ('Escalade ESV', 117);
insert into train (model, capacity) values ('Camaro', 177);
insert into train (model, capacity) values ('ES', 112);
insert into train (model, capacity) values ('RX', 156);
insert into train (model, capacity) values ('6000', 130);
insert into train (model, capacity) values ('Freelander', 154);
insert into train (model, capacity) values ('Continental', 123);
insert into train (model, capacity) values ('S-Class', 143);
insert into train (model, capacity) values ('Ram 3500', 102);
insert into train (model, capacity) values ('Pathfinder', 100);
insert into train (model, capacity) values ('ES', 170);
insert into train (model, capacity) values ('SL-Class', 118);
insert into train (model, capacity) values ('Versa', 114);
insert into train (model, capacity) values ('F350', 181);
insert into train (model, capacity) values ('Continental', 154);
insert into train (model, capacity) values ('XJ Series', 114);
insert into train (model, capacity) values ('LX', 125);
insert into train (model, capacity) values ('G-Series G30', 148);
insert into train (model, capacity) values ('Z4 M', 102);
insert into train (model, capacity) values ('SVX', 121);
insert into train (model, capacity) values ('Esprit', 149);
insert into train (model, capacity) values ('Neon', 194);
insert into train (model, capacity) values ('88', 103);
insert into train (model, capacity) values ('Pajero', 196);
insert into train (model, capacity) values ('Expedition EL', 136);
insert into train (model, capacity) values ('S80', 174);
insert into train (model, capacity) values ('Navigator L', 186);
insert into train (model, capacity) values ('RX-8', 128);
insert into train (model, capacity) values ('Countach', 146);
insert into train (model, capacity) values ('Tempo', 190);
insert into train (model, capacity) values ('Cougar', 196);
insert into train (model, capacity) values ('Interceptor', 138);
insert into train (model, capacity) values ('Aerio', 102);
insert into train (model, capacity) values ('Sonata', 182);
insert into train (model, capacity) values ('Firebird', 160);
insert into train (model, capacity) values ('Escort', 141);
insert into train (model, capacity) values ('LX', 162);
insert into train (model, capacity) values ('Dakota', 179);
insert into train (model, capacity) values ('Liberty', 191);
insert into train (model, capacity) values ('Explorer Sport Trac', 170);
insert into train (model, capacity) values ('A4', 191);
insert into train (model, capacity) values ('Challenger', 165);
insert into train (model, capacity) values ('Pilot', 122);
insert into train (model, capacity) values ('Capri', 142);
insert into train (model, capacity) values ('5000CS', 200);
insert into train (model, capacity) values ('Savana', 146);
insert into train (model, capacity) values ('Ranger', 144);
insert into train (model, capacity) values ('QX', 150);
insert into train (model, capacity) values ('Windstar', 183);
insert into train (model, capacity) values ('Blazer', 141);
insert into train (model, capacity) values ('Galant', 134);
insert into train (model, capacity) values ('Express 2500', 176);
insert into train (model, capacity) values ('Sky', 135);
insert into train (model, capacity) values ('Grand Prix', 139);
insert into train (model, capacity) values ('Eldorado', 102);
insert into train (model, capacity) values ('XC60', 200);
insert into train (model, capacity) values ('100', 195);
insert into train (model, capacity) values ('Ranger', 146);
insert into train (model, capacity) values ('Escort', 163);
insert into train (model, capacity) values ('Land Cruiser', 149);
insert into train (model, capacity) values ('9-3', 109);
insert into train (model, capacity) values ('Cutlass Supreme', 132);
insert into train (model, capacity) values ('X3', 188);
insert into train (model, capacity) values ('RL', 143);
insert into train (model, capacity) values ('Breeze', 153);
insert into train (model, capacity) values ('Laser', 112);
insert into train (model, capacity) values ('Altima', 125);
insert into train (model, capacity) values ('SX4', 113);
insert into train (model, capacity) values ('Monte Carlo', 179);
insert into train (model, capacity) values ('Phaeton', 127);
insert into train (model, capacity) values ('T100 Xtra', 101);
insert into train (model, capacity) values ('Ram Van 1500', 161);
insert into train (model, capacity) values ('Grand Prix', 185);
insert into train (model, capacity) values ('Durango', 125);
insert into train (model, capacity) values ('Z4 M', 170);
insert into train (model, capacity) values ('Cabriolet', 194);
insert into train (model, capacity) values ('LeMans', 182);
insert into train (model, capacity) values ('3500 Club Coupe', 182);
insert into train (model, capacity) values ('C-Class', 135);
insert into train (model, capacity) values ('Galant', 148);
insert into train (model, capacity) values ('M3', 185);
insert into train (model, capacity) values ('Enclave', 189);
insert into train (model, capacity) values ('Corvette', 135);
insert into train (model, capacity) values ('90', 185);
insert into train (model, capacity) values ('Highlander', 121);
insert into train (model, capacity) values ('Galant', 130);
insert into train (model, capacity) values ('Brat', 188);
insert into train (model, capacity) values ('7 Series', 166);
insert into train (model, capacity) values ('Liberty', 190);
insert into train (model, capacity) values ('F450', 116);
insert into train (model, capacity) values ('Lumina', 153);
insert into train (model, capacity) values ('Kizashi', 149);
insert into train (model, capacity) values ('Sierra', 197);
insert into train (model, capacity) values ('Wrangler', 100);
insert into train (model, capacity) values ('Continental Flying Spur', 166);
insert into train (model, capacity) values ('TSX', 179);
insert into train (model, capacity) values ('Defender', 182);
insert into train (model, capacity) values ('Cooper Clubman', 148);
insert into train (model, capacity) values ('TL', 150);
insert into train (model, capacity) values ('Outback', 178);
insert into train (model, capacity) values ('MX-6', 174);
insert into train (model, capacity) values ('Suburban 1500', 134);
insert into train (model, capacity) values ('Accord', 174);
insert into train (model, capacity) values ('Ranger', 193);
insert into train (model, capacity) values ('Aurora', 129);
insert into train (model, capacity) values ('Ram 1500', 170);
insert into train (model, capacity) values ('Sorento', 164);
insert into train (model, capacity) values ('Hombre Space', 186);
insert into train (model, capacity) values ('Sierra 2500', 133);
insert into train (model, capacity) values ('Grand Voyager', 115);
insert into train (model, capacity) values ('911', 181);
insert into train (model, capacity) values ('Alcyone SVX', 160);
insert into train (model, capacity) values ('Civic', 125);
insert into train (model, capacity) values ('Allroad', 183);
insert into train (model, capacity) values ('Passat', 114);
insert into train (model, capacity) values ('M', 160);
insert into train (model, capacity) values ('Bravada', 176);
insert into train (model, capacity) values ('Q', 120);
insert into train (model, capacity) values ('Century', 171);
insert into train (model, capacity) values ('Sigma', 164);
insert into train (model, capacity) values ('Fox', 181);
insert into train (model, capacity) values ('M5', 181);
insert into train (model, capacity) values ('Frontier', 199);
insert into train (model, capacity) values ('XLR-V', 173);
insert into train (model, capacity) values ('Alliance', 187);
insert into train (model, capacity) values ('Montana', 191);
insert into train (model, capacity) values ('Millenia', 169);
insert into train (model, capacity) values ('90', 103);
insert into train (model, capacity) values ('XJ Series', 109);
insert into train (model, capacity) values ('Maxima', 126);
insert into train (model, capacity) values ('C70', 198);
insert into train (model, capacity) values ('S80', 115);
insert into train (model, capacity) values ('RX', 113);
insert into train (model, capacity) values ('Outback', 184);
insert into train (model, capacity) values ('Sentra', 100);
insert into train (model, capacity) values ('Eclipse', 145);
insert into train (model, capacity) values ('Cayman', 112);
insert into train (model, capacity) values ('900', 123);
insert into train (model, capacity) values ('Lanos', 145);
insert into train (model, capacity) values ('Spectra', 184);
insert into train (model, capacity) values ('Fiesta', 120);
insert into train (model, capacity) values ('5 Series', 174);
insert into train (model, capacity) values ('Suburban', 196);
insert into train (model, capacity) values ('XC70', 113);
insert into train (model, capacity) values ('Aurora', 136);
insert into train (model, capacity) values ('Escalade EXT', 193);
insert into train (model, capacity) values ('Tempest', 157);
insert into train (model, capacity) values ('Continental Mark VII', 157);
insert into train (model, capacity) values ('Grand Vitara', 178);
insert into train (model, capacity) values ('Yukon XL 2500', 139);
insert into train (model, capacity) values ('Swift', 135);
insert into train (model, capacity) values ('Eldorado', 183);
insert into train (model, capacity) values ('Forester', 173);
insert into train (model, capacity) values ('Pathfinder', 156);
insert into train (model, capacity) values ('VehiCROSS', 157);
insert into train (model, capacity) values ('Vibe', 137);
insert into train (model, capacity) values ('928', 134);
insert into train (model, capacity) values ('Ram Van B250', 174);
insert into train (model, capacity) values ('Galant', 156);
insert into train (model, capacity) values ('Metro', 179);
insert into train (model, capacity) values ('Yukon', 192);
insert into train (model, capacity) values ('Escape', 145);
insert into train (model, capacity) values ('Xterra', 140);
insert into train (model, capacity) values ('Land Cruiser', 169);
insert into train (model, capacity) values ('Grand Marquis', 153);
insert into train (model, capacity) values ('Eclipse', 114);
insert into train (model, capacity) values ('Echo', 197);
insert into train (model, capacity) values ('Montana', 179);
insert into train (model, capacity) values ('Rio', 167);
insert into train (model, capacity) values ('GS', 178);
insert into train (model, capacity) values ('Quattroporte', 186);
insert into train (model, capacity) values ('RL', 156);
insert into train (model, capacity) values ('Silverado', 152);
insert into train (model, capacity) values ('LR3', 140);
insert into train (model, capacity) values ('Pacifica', 163);
insert into train (model, capacity) values ('Vandura G2500', 126);
insert into train (model, capacity) values ('Grand Voyager', 156);
insert into train (model, capacity) values ('GS', 145);
insert into train (model, capacity) values ('6 Series', 116);
insert into train (model, capacity) values ('H1', 137);
insert into train (model, capacity) values ('Clubman', 166);
insert into train (model, capacity) values ('5 Series', 165);
insert into train (model, capacity) values ('Touareg', 147);
insert into train (model, capacity) values ('Golf', 124);
insert into train (model, capacity) values ('M5', 146);
insert into train (model, capacity) values ('SX4', 148);
insert into train (model, capacity) values ('Maxima', 159);
insert into train (model, capacity) values ('RX-8', 139);
insert into train (model, capacity) values ('CL-Class', 125);
insert into train (model, capacity) values ('Century', 139);
insert into train (model, capacity) values ('Samurai', 103);
insert into train (model, capacity) values ('Z4', 199);
insert into train (model, capacity) values ('Acclaim', 194);
insert into train (model, capacity) values ('Legacy', 141);
insert into train (model, capacity) values ('Mini', 172);
insert into train (model, capacity) values ('EX', 197);
insert into train (model, capacity) values ('Ram Wagon B250', 101);
insert into train (model, capacity) values ('Park Avenue', 139);
